---

- hosts: all
  become: true

# Pre Tasks

  pre_tasks:

  - name: Remove unnecessary apps
    tags: always
    apt:
      state: absent
      pkg:
      - aisleriot
      - gnome-mahjongg
      - gnome-mines
      - gnome-sudoku
      - usb-creator-common
      - usb-creator-gtk
      - transmission-common
      - transmission-gtk

  - name: Apt update && upgrade
    tags: always
    apt:
      update_cache: yes
      upgrade: 'yes'

  - name: Update apps
    tags: always
    command: snap refresh

  - name: Install Open-VM-Tools
    tags: vsphere
    apt:
      state: latest
      pkg:
      - open-vm-tools-desktop

  - name: Install new apps
    tags: always
    snap:
      name:
      - chromium
      - p7zip-desktop
      - telegram-desktop
      - vlc
      - zoom-client

  - name: Disable automatic updates
    tags: always
    replace:
      path: /etc/apt/apt.conf.d/20auto-upgrades
      regexp: '(^APT::Periodic::Update-Package-Lists \")1(\")'
      replace: '\g<1>0\g<2>'

  - name: Disable unattended upgrades
    tags: always
    replace:
      path: /etc/apt/apt.conf.d/20auto-upgrades
      regexp: '(^APT::Periodic::Unattended-Upgrade \")1(\")'
      replace: '\g<1>0\g<2>'  

  - name: Install apps for domain join
    tags: domain
    apt:
     state: latest
     pkg:
     - sssd-ad
     - sssd-tools
     - realmd
     - adcli
     - krb5-user

  - name: Copy Horizon Agent installer
    tags: horizon
    unarchive:
      src: '{{ horizon_agent }}'
      dest: /tmp/
      extra_opts:
      - --one-top-level=horizonagent
      - --strip-components=1

  - name: Copy VHCI Driver for USB redirection
    tags: horizon
    unarchive:
      src: '{{ vhci_driver }}'
      dest: /tmp
      extra_opts:
      - --one-top-level=vhci
      - --strip-components=1

  - name: Copy V4L2Loopback Driver for RTAV
    tags: horizon
    unarchive:
      src: '{{ v4l2loopback_driver }}'
      dest: /tmp
      extra_opts:
      - --one-top-level=v4l2loopback
      - --strip-components=1

  - name: Install make, gcc, libelf-dev, linux-headers
    tags: horizon
    apt:
      name:
      - make
      - gcc
      - libelf-dev
      - linux-headers-{{ ansible_kernel }}
      state: latest 

  - name: Install packages for Horizon agent
    tags: horizon
    apt:
      name:
      - python
      - python-dbus
      - python-gobject
    when: ansible_distribution_version == "18.04"


# Tasks

  tasks:

  - name: Enable GRUB quiet boot
    tags: always
    replace:
      path: /etc/default/grub
      regexp: '(^GRUB_CMDLINE_LINUX_DEFAULT=\").*(\")'
      replace: '\g<1>quiet\g<2>'
    register: grub_update

  - name: Reload GRUB
    tags: always
    command: update-grub
    when: grub_update.changed == True

  - name: Disable hibernation and sleep
    tags: always
    command: systemctl mask sleep.target suspend.target hibernate.target hybrid-sleep.target

  - name: Disable unnecessary services
    tags: always
    service:
      name: "{{ item }}"
      state: stopped
      enabled: no
    loop:
    - bluetooth
    - bolt
    - fwupd

  - name: Join to domain
    tags: domain
    shell: |
      echo "{{ domain_password }}" | realm join -U "{{ domain_user }}" "{{ domain_name }}"
      pam-auth-update --enable mkhomedir

  - name: Enable TKT rc4-hmac encryption for Ubuntu 18.04
    tags: domain
    lineinfile:
      path: /etc/krb5.conf
      line: 'default_tkt_enctypes = rc4-hmac'
      create: yes
    when: ansible_distribution_version == "18.04"

  - name: Enable TGS rc4-hmac encryption for Ubuntu 18.04
    tags: domain
    lineinfile:
      path: /etc/krb5.conf
      line: 'default_tgs_enctypes = rc4-hmac'
      create: yes
    when: ansible_distribution_version == "18.04"

  - name: Install VHCI driver
    tags: horizon
    shell: |
      cd /tmp/vhci
      patch -p1 < /tmp/horizonagent/resources/vhci/patch/vhci.patch
      make clean && make && make install

  - name: Install V4L2Loopback driver
    tags: horizon
    shell: |
      cd /tmp/v4l2loopback
      patch -p1 < /tmp/horizonagent/resources/v4l2loopback/v4l2loopback.patch
      make clean && make && make install
      make install-utils
      depmod -A

  - name: Override V4L2Loopback driver for Ubuntu 22.04
    tags: horizon
    lineinfile:
      path: /etc/depmod.d/ubuntu.conf
      line: override v4l2loopback * extra
      create: yes    
    when: ansible_distribution_version == "22.04"

  - name: Regenerate modules.dep file
    tags: horizon
    shell: |
      depmod -a
    when: ansible_distribution_version == "22.04"

  - name: Install Horizon Agent
    tags: horizon
    shell: |
      cd /tmp/horizonagent
      ./install_viewagent.sh -A yes -U yes -a yes -m yes --webcam
    register: horizonagent_install

  - name: Enable Horizon offline domain join
    tags: domain
    lineinfile:
      path: /etc/vmware/viewagent-custom.conf
      line: OfflineJoinDomain=sssd
      create: yes
    when: horizonagent_install.changed == True   

  - name: Enable SSO with Horizon
    tags: horizon
    lineinfile:
      path: /etc/sssd/sssd.conf
      line: 'ad_gpo_map_interactive = +gdm-vmwcred'
      create: yes

  - name: Deactivate GPO access control in the cloned VM
    tags: horizon
    lineinfile:
      path: /etc/sssd/sssd.conf
      line: 'ad_gpo_access_control = permissive'
      create: yes

  - name: Set Horizon SSO user format to domain\username
    tags: horizon
    lineinfile:
      path: /etc/vmware/viewagent-custom.conf
      line: 'SSOUserFormat=[domain]\\[username]'
      create: yes


# Post Tasks

  post_tasks:

  - name: Disable automatic screen brightness, animation, and suspend
    become: false
    tags: gnome
    shell: |
      gsettings set org.gnome.settings-daemon.plugins.power ambient-enabled false
      gsettings set org.gnome.settings-daemon.plugins.power idle-dim false
      gsettings set org.gnome.settings-daemon.plugins.power sleep-inactive-ac-type 'nothing'
      gsettings set org.gnome.settings-daemon.plugins.power sleep-inactive-battery-type 'suspend'
      gsettings set org.gnome.desktop.interface enable-animations 'false'
    register: profile_update

  - name: Set desktop color and theme
    become: false
    tags: gnome
    shell: |
      gsettings set org.gnome.desktop.background picture-uri ''
      gsettings set org.gnome.desktop.background primary-color '#0063B2'
      gsettings set org.gnome.desktop.interface gtk-theme 'Yaru-blue'      
    register: profile_update

  - name: Create dconf directory to copy GNOME config 
    tags: gnome
    file:
      path: /etc/skel/.config/dconf
      state: directory
      mode: '0700'
    when: profile_update.changed == True

  - name: Copy GNOME config
    tags: gnome
    command: cp /home/{{ ansible_user }}/.config/dconf/user /etc/skel/.config/dconf/user
    when: profile_update.changed == True

  - name: Disable GNOME Welcome screen
    tags: gnome
    copy:
      dest: /etc/skel/.config/gnome-initial-setup-done
      mode: '0664'
      content: |
        yes
    when: profile_update.changed == True

  - name: Clear bash history
    tags: always
    shell: |
      rm ~/.bash_history
      echo 'history -c' >> ~/.bash_logout
    args:
      warn: false

  - name: Reboot the host
    tags: reboot
    reboot:
      reboot_timeout: 300

#  - name: Create test user account
#    user:
#      name: test
#      shell: /bin/bash
#      password: '$6$zMBWwUkBVcgrre7j$G8ecTKBZ9kal1nox9Jagge8hE.U5IPOw0SiVyS.jGBdLZ78ZCyf83dLfbYPJK.us4r1lWR/VVefk5/86MyRQx.'
#      groups: root





